package guiwebbanking;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

import clasesSWB.PersistenceManager;

import javax.swing.JOptionPane;


/**
 *
 * @author MAN-U
 */
public class Login extends javax.swing.JFrame {
    private int intentosFallidos = 0;
    private PersistenceManager persistenceManager;
    private GUI guiWebBanking;
    /**
     * Creates new form GUIWebBanking
     */
    public Login() {
        initComponents();
        // cambia la posición de la ventana al ejecutarse la aplicación
        setLocationRelativeTo(null);
        // cambia las propiedades de algunos widgets del login
        changeComponentsproperties();
    }

    public void inicializarPersistenceManager(PersistenceManager persistenceManager){
        this.persistenceManager = persistenceManager;
    }
    
    public void inicializarGUI(GUI guiWebBanking){
        this.guiWebBanking = guiWebBanking;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new FondoPanel();
        jPanelLogin = new FondoPanel();
        jLabelTituloLogin = new javax.swing.JLabel();
        jButtonDocumentacion = new javax.swing.JButton();
        jPanelenjPanelLogin = new javax.swing.JPanel();
        jTextNumeroCuenta = new javax.swing.JTextField();
        jLabelPINCuenta = new javax.swing.JLabel();
        jPasswordPINCuenta = new javax.swing.JPasswordField();
        jLabelNumeroCuenta = new javax.swing.JLabel();
        panelIngresar = new java.awt.Panel();
        jLabelIngresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1051, 700));

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setPreferredSize(new java.awt.Dimension(1051, 700));

        jPanelLogin.setPreferredSize(new java.awt.Dimension(1051, 700));

        jLabelTituloLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 76)); // NOI18N
        jLabelTituloLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloLogin.setText("Sistema Web Banking");
        jLabelTituloLogin.setAlignmentX(0.5F);
        jLabelTituloLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTituloLogin.setPreferredSize(new java.awt.Dimension(1100, 131));

        jButtonDocumentacion.setBackground(new java.awt.Color(0, 0, 0));
        jButtonDocumentacion.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonDocumentacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDocumentacion.setText("<html><u>Acerca del Sistema ></u></html>");
        jButtonDocumentacion.setBorder(null);
        jButtonDocumentacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDocumentacion.setInheritsPopupMenu(true);
        jButtonDocumentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDocumentacionActionPerformed(evt);
            }
        });

        jPanelenjPanelLogin.setAlignmentX(0.0F);
        jPanelenjPanelLogin.setAlignmentY(0.0F);
        jPanelenjPanelLogin.setPreferredSize(new java.awt.Dimension(500, 427));
        jPanelenjPanelLogin.setLayout(null);

        jTextNumeroCuenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextNumeroCuenta.setAlignmentX(0.7F);
        jTextNumeroCuenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextNumeroCuenta.setOpaque(true);
        jTextNumeroCuenta.setPreferredSize(new java.awt.Dimension(380, 40));
        jTextNumeroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroCuentaActionPerformed(evt);
            }
        });
        jTextNumeroCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNumeroCuentaKeyPressed(evt);
            }
        });
        jPanelenjPanelLogin.add(jTextNumeroCuenta);
        jTextNumeroCuenta.setBounds(100, 80, 380, 40);

        jLabelPINCuenta.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabelPINCuenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPINCuenta.setText("PIN:");
        jLabelPINCuenta.setAlignmentX(0.5F);
        jLabelPINCuenta.setPreferredSize(new java.awt.Dimension(380, 54));
        jPanelenjPanelLogin.add(jLabelPINCuenta);
        jLabelPINCuenta.setBounds(100, 144, 380, 54);

        jPasswordPINCuenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPasswordPINCuenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPasswordPINCuenta.setOpaque(true);
        jPasswordPINCuenta.setPreferredSize(new java.awt.Dimension(380, 40));
        jPasswordPINCuenta.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPasswordPINCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordPINCuentaActionPerformed(evt);
            }
        });
        jPasswordPINCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordPINCuentaKeyPressed(evt);
            }
        });
        jPanelenjPanelLogin.add(jPasswordPINCuenta);
        jPasswordPINCuenta.setBounds(100, 200, 380, 40);

        jLabelNumeroCuenta.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabelNumeroCuenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNumeroCuenta.setText("Número de Cuenta:");
        jLabelNumeroCuenta.setAlignmentX(0.5F);
        jLabelNumeroCuenta.setPreferredSize(new java.awt.Dimension(380, 54));
        jPanelenjPanelLogin.add(jLabelNumeroCuenta);
        jLabelNumeroCuenta.setBounds(100, 20, 380, 54);

        panelIngresar.setBackground(new java.awt.Color(0, 51, 102));

        jLabelIngresar.setBackground(new java.awt.Color(17, 44, 71));
        jLabelIngresar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIngresar.setText("INGRESAR >");
        jLabelIngresar.setPreferredSize(new java.awt.Dimension(223, 91));
        jLabelIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIngresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelIngresarLayout = new javax.swing.GroupLayout(panelIngresar);
        panelIngresar.setLayout(panelIngresarLayout);
        panelIngresarLayout.setHorizontalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelIngresarLayout.setVerticalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelenjPanelLogin.add(panelIngresar);
        panelIngresar.setBounds(170, 290, 245, 100);

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTituloLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jPanelenjPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(245, 245, 245))
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButtonDocumentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabelTituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelenjPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonDocumentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Método que cambia las propiedades de los widgets del Login (colores y ubicación).
     */
    private void changeComponentsproperties(){
        // Desactivar la opacidad del fondo
        jButtonDocumentacion.setOpaque(false);

        // Establecer un fondo transparente
        jButtonDocumentacion.setBackground(new Color(0, 0, 0, 0));
        
        // Hace transparente los jPanels que contiene los widgets del Login
        jPanelLogin.setBackground(new Color(0, 0, 0, 0));
        jPanelenjPanelLogin.setBackground(new Color(0, 0, 0, 0));
        
        // cambia el layout del jPanel con los widgets del login para que se mantengan centrados
        // aunque la ventana cambie de tamaño
        jPanelenjPanelLogin.setLayout(new GridBagLayout()); // permite declarar un nuevo layout 
                                                            //en este caso como una mochila de
                                                            //columnas y filas para posicionar los widgets
                                                            //en el jPanel
        //declara una nueva variable tipo GridBagConstraints
        GridBagConstraints gridBagConstraints = new GridBagConstraints(); 
        
        gridBagConstraints.gridy = 0; //columna en la que estará ubicado el widget
        
        gridBagConstraints.gridx = 0; //fila en la que estará ubicado el widget
        
        gridBagConstraints.insets = new Insets(5, 5, 5, 5); //el espaciado generado entre otros widgets
        
        //agrega el widget al jPanel con las configuraciones de gridBagConstraints
        jPanelenjPanelLogin.add(jLabelNumeroCuenta, gridBagConstraints); 
        
        // repite el proceso anterior para cada widget que se quiere ubicar en el jPanel
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 2; 
        jPanelenjPanelLogin.add(jLabelPINCuenta, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 1; 
        jPanelenjPanelLogin.add(jTextNumeroCuenta, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jPanelenjPanelLogin.add(jPasswordPINCuenta, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new Insets(40, 40, 40, 40);
        jPanelenjPanelLogin.add(panelIngresar, gridBagConstraints);
        
    }
    
    private void jButtonDocumentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDocumentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDocumentacionActionPerformed

    private void jTextNumeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroCuentaActionPerformed

    private void jPasswordPINCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordPINCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordPINCuentaActionPerformed

    /**
     * 
     * @param evt 
     */
    private void jLabelIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIngresarMouseClicked
        // Obtener el número de cuenta y el PIN ingresados por el usuario
        String IDCuenta = jTextNumeroCuenta.getText();
        String pin = new String(jPasswordPINCuenta.getPassword());
        
        // Validar el inicio de sesión
        if (persistenceManager.validarInicioSesion(IDCuenta, pin) && intentosFallidos < 3) {

            // Si la validación es exitosa, abrir la ventana principal
            VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
            ventanaPrincipal.setVisible(true);
            
            // llamada al método que instancia la cuenta accedida en la ventana principal
            ventanaPrincipal.InicializarCuenta(IDCuenta, persistenceManager);
            ventanaPrincipal.inicializarGUI(guiWebBanking);
            
            this.dispose();
            
        } else {
            intentosFallidos++;
            // Si la validación falla, mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "Inicio de sesión fallido. Por favor, verifica tu número de cuenta y PIN.", "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
        }
        
        if (intentosFallidos >= 3){
            System.out.print("This acount is baned");
            JOptionPane.showMessageDialog(this, "Su cuenta ha sido bloqueada temporalmente, acuda al servicio telefónico", "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelIngresarMouseClicked

    /**
     * Método que cambia el color del fondo del jLabel que representa el botón de
     * ingreso a la ventana principal desde el login al entrar al dominio del widget
     * @param evt Objeto MouseEvent que representa la acción del mouse, los clicks
     * y la entrada dentro de los dominios de los widgets
     */
    private void jLabelIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIngresarMouseEntered
        panelIngresar.setBackground(new Color(17,44,71));
    }//GEN-LAST:event_jLabelIngresarMouseEntered
    /**
     * Método que cambia el color del fondo del jLabel que representa el botón de
     * ingreso a la ventana principal desde el login al salir del dominio del widget
     * @param evt Objeto MouseEvent que representa la acción del mouse, los clicks
     * y la entrada dentro de los dominios de los widgets
     */
    private void jLabelIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIngresarMouseExited
        panelIngresar.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabelIngresarMouseExited

    /**
     * Método que maneja el evento cuando una tecla es presionada en el campo de texto
     * para ingresar el número de cuenta.
     * @param evt Objeto KeyEvent que representa el evento de teclado.
     */
    private void jTextNumeroCuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNumeroCuentaKeyPressed
        // Verificar si la tecla presionada es la tecla "Enter"
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Cuando se presiona "Enter", establecer el foco en el campo de texto para el PIN de la cuenta
            jPasswordPINCuenta.requestFocus();
        }
    }//GEN-LAST:event_jTextNumeroCuentaKeyPressed
    /**
     * Método que maneja el evento cuando una tecla es presionada en el campo de texto
     * para ingresar el pin de la cuenta, lo lleva directo a la función que valida los datos
     * para ingresar a la app.
     * @param evt Objeto KeyEvent que representa el evento de teclado.
     */
    private void jPasswordPINCuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordPINCuentaKeyPressed
        // Verificar si la tecla presionada es la tecla "Enter"
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            // Cuando se presiona "Enter", llama a la función que maneja el evento
            // de clicked del jLabelIngresar(simula el botón de ingreso)
            jLabelIngresarMouseClicked(null);
        }
    }//GEN-LAST:event_jPasswordPINCuentaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDocumentacion;
    private javax.swing.JLabel jLabelIngresar;
    private javax.swing.JLabel jLabelNumeroCuenta;
    private javax.swing.JLabel jLabelPINCuenta;
    private javax.swing.JLabel jLabelTituloLogin;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelenjPanelLogin;
    private javax.swing.JPasswordField jPasswordPINCuenta;
    private javax.swing.JTextField jTextNumeroCuenta;
    private java.awt.Panel panelIngresar;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Clase FondoPanel que extiende JPanel y muestra una imagen como fondo de la app.
     */
    class FondoPanel extends JPanel {
        private final Image imagen;

        /**
         * Constructor de la clase. Carga la imagen en el fondo.
         */
        public FondoPanel() {
            // Carga la imagen desde el recurso del proyecto
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondobanco.jpg")).getImage();

            // Establece la opacidad del panel como transparente
            setOpaque(false);
        }

        /**
         * Método paint que se llama automáticamente cuando se necesita pintar el componente.
         * @param g El contexto gráfico utilizado para dibujar.
         */
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);

            // Dibuja la imagen en el fondo del panel con el tamaño del panel
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    }
    
}//Cierre de la clase
