package guiwebbanking;

import Contenidos.PanelDeposito;
import Contenidos.PanelHistorial;
import Contenidos.Inicio;
import Contenidos.PanelMiCuenta;
import Contenidos.PanelPagarMisTarjetas;
import Contenidos.PanelPagarOtrasTarjetas;
import Contenidos.PanelPagos;
import Contenidos.PanelTransferencia;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;

import clasesSWB.PersistenceManager;
import clasesSWB.Cuenta;
import clasesSWB.Cliente;

/**
 *
 * @author MAN-U
 */
public class VentanaPrincipal extends javax.swing.JFrame{
    private Inicio inicio;
    private PanelMiCuenta Panelmicuenta;
    private PanelPagarOtrasTarjetas Panelpagarotrastarjetas;
    private PanelPagarMisTarjetas Panelpagarmistarjetas;
    private PanelTransferencia Paneltransferencia;
    private PanelDeposito Paneldeposito;
    private PanelPagos Panelpagos;
    private PanelHistorial Panelhistorial;
    
    private PersistenceManager persistenceManager;
    private Cuenta cuenta;
    private Cliente cliente;
    
    private GUI guiWebBanking;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        changeComponentsProperties();      
        
        //jLabelBotonInicioMouseClicked(null); //al desplegarse la ventana principal
                                            //se llama al método mouseclicked del boton
                                            //inicio para agregar un JPanel de la clase
                                            //inicio al jPanelContenido 
    }

    /**
     * Método que inicializa los atributos de cuenta y cliente.
     */
    public void InicializarCuenta(String IDCuenta, PersistenceManager persistenceManager){
        this.persistenceManager = persistenceManager;
        this.cuenta = persistenceManager.getCuenta(IDCuenta);
        cliente = persistenceManager.getCliente(cuenta.getIDCliente());
        inicio = new Inicio(persistenceManager);
        Panelmicuenta = new PanelMiCuenta(persistenceManager);
        Panelpagarotrastarjetas = new PanelPagarOtrasTarjetas();
        Panelpagarmistarjetas = new PanelPagarMisTarjetas();
        Paneltransferencia = new PanelTransferencia(persistenceManager, cliente);
        Paneldeposito = new PanelDeposito(persistenceManager);
        Panelpagos = new PanelPagos();
        Panelhistorial = new PanelHistorial();
    }
    
    public void inicializarGUI(GUI guiWebBanking){
        this.guiWebBanking = guiWebBanking;
    }
    
    /**
     * Método que cambia el color y la transparencia del jPanelContenido y jPanelToolBar.
     */

    public final void changeComponentsProperties(){
        jPanelContenido.setBackground(new Color(0, 0, 0, 0));
        jPanelToolBar.setBackground(new Color(0, 0, 0, 0));  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new FondoPanel();
        jPanelMenu = new javax.swing.JPanel();
        jPanelIconoMenu = new javax.swing.JPanel();
        jLabelTituloMenu = new javax.swing.JLabel();
        jLabelIconoMenu = new javax.swing.JLabel();
        jPanelInicio = new javax.swing.JPanel();
        jLabelBotonInicio = new javax.swing.JLabel();
        jPanelMiCuenta = new javax.swing.JPanel();
        jLabelBotonMiCuenta = new javax.swing.JLabel();
        jPanelTarjetas = new javax.swing.JPanel();
        jLabelBotonTarjetas = new javax.swing.JLabel();
        jPanelTransacciones = new javax.swing.JPanel();
        jLabelBotonTransacciones = new javax.swing.JLabel();
        jPanelDeposito = new javax.swing.JPanel();
        jLabelBotonDeposito = new javax.swing.JLabel();
        jPanelOpcionesTarjetas = new javax.swing.JPanel();
        jLabelPagarOtrasTarjetas = new javax.swing.JLabel();
        jLabelPagarMisTarjetas = new javax.swing.JLabel();
        jPanelPagos = new javax.swing.JPanel();
        jLabelBotonPagos = new javax.swing.JLabel();
        jPanelHistorial = new javax.swing.JPanel();
        jLabelBotonHistorial = new javax.swing.JLabel();
        jPanelOpcionesTransacciones = new javax.swing.JPanel();
        jLabelTransferencia = new javax.swing.JLabel();
        jPanelCerrarSesion = new javax.swing.JPanel();
        jLabelBotonCerrarSesion = new javax.swing.JLabel();
        jPanelContenido = new javax.swing.JPanel();
        jPanelToolBar = new javax.swing.JPanel();
        jLabelBotonDesplegarMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Web Banking");
        setMinimumSize(new java.awt.Dimension(1051, 700));

        jPanelFondo.setPreferredSize(new java.awt.Dimension(1051, 700));

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setAlignmentX(0.0F);
        jPanelMenu.setAlignmentY(0.0F);
        jPanelMenu.setPreferredSize(new java.awt.Dimension(290, 700));

        jPanelIconoMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelIconoMenu.setPreferredSize(new java.awt.Dimension(290, 160));

        jLabelTituloMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/titulomenu.png"))); // NOI18N
        jLabelTituloMenu.setPreferredSize(new java.awt.Dimension(146, 140));

        jLabelIconoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconomenu.png"))); // NOI18N
        jLabelIconoMenu.setText("jLabel2");

        javax.swing.GroupLayout jPanelIconoMenuLayout = new javax.swing.GroupLayout(jPanelIconoMenu);
        jPanelIconoMenu.setLayout(jPanelIconoMenuLayout);
        jPanelIconoMenuLayout.setHorizontalGroup(
            jPanelIconoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIconoMenuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelIconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTituloMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelIconoMenuLayout.setVerticalGroup(
            jPanelIconoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIconoMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelIconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelIconoMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTituloMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelInicio.setBackground(new java.awt.Color(0, 51, 102));
        jPanelInicio.setPreferredSize(new java.awt.Dimension(290, 50));

        jLabelBotonInicio.setBackground(new java.awt.Color(68, 114, 196));
        jLabelBotonInicio.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelBotonInicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa.png"))); // NOI18N
        jLabelBotonInicio.setText("Inicio");
        jLabelBotonInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelBotonInicio.setOpaque(true);
        jLabelBotonInicio.setPreferredSize(new java.awt.Dimension(290, 50));
        jLabelBotonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBotonInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotonInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelMiCuenta.setBackground(new java.awt.Color(0, 51, 102));
        jPanelMiCuenta.setMinimumSize(new java.awt.Dimension(290, 60));
        jPanelMiCuenta.setPreferredSize(new java.awt.Dimension(290, 50));

        jLabelBotonMiCuenta.setBackground(new java.awt.Color(68, 114, 196));
        jLabelBotonMiCuenta.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelBotonMiCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBotonMiCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil.png"))); // NOI18N
        jLabelBotonMiCuenta.setText("Mi Cuenta  ");
        jLabelBotonMiCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelBotonMiCuenta.setOpaque(true);
        jLabelBotonMiCuenta.setPreferredSize(new java.awt.Dimension(290, 50));
        jLabelBotonMiCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonMiCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBotonMiCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotonMiCuentaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelMiCuentaLayout = new javax.swing.GroupLayout(jPanelMiCuenta);
        jPanelMiCuenta.setLayout(jPanelMiCuentaLayout);
        jPanelMiCuentaLayout.setHorizontalGroup(
            jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                .addComponent(jLabelBotonMiCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMiCuentaLayout.setVerticalGroup(
            jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                .addComponent(jLabelBotonMiCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelTarjetas.setBackground(new java.awt.Color(0, 51, 102));
        jPanelTarjetas.setPreferredSize(new java.awt.Dimension(290, 50));
        jPanelTarjetas.setLayout(null);

        jLabelBotonTarjetas.setBackground(new java.awt.Color(68, 114, 196));
        jLabelBotonTarjetas.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelBotonTarjetas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBotonTarjetas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonTarjetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjeta-de-credito.png"))); // NOI18N
        jLabelBotonTarjetas.setText("Tarjetas              +");
        jLabelBotonTarjetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelBotonTarjetas.setOpaque(true);
        jLabelBotonTarjetas.setPreferredSize(new java.awt.Dimension(260, 50));
        jLabelBotonTarjetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonTarjetasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBotonTarjetasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotonTarjetasMouseExited(evt);
            }
        });
        jPanelTarjetas.add(jLabelBotonTarjetas);
        jLabelBotonTarjetas.setBounds(0, 0, 290, 50);

        jPanelTransacciones.setBackground(new java.awt.Color(0, 51, 102));
        jPanelTransacciones.setPreferredSize(new java.awt.Dimension(290, 50));
        jPanelTransacciones.setLayout(null);

        jLabelBotonTransacciones.setBackground(new java.awt.Color(68, 114, 196));
        jLabelBotonTransacciones.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelBotonTransacciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBotonTransacciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBotonTransacciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/transaccion.png"))); // NOI18N
        jLabelBotonTransacciones.setText("Transacciones    +");
        jLabelBotonTransacciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelBotonTransacciones.setOpaque(true);
        jLabelBotonTransacciones.setPreferredSize(new java.awt.Dimension(260, 50));
        jLabelBotonTransacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonTransaccionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBotonTransaccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotonTransaccionesMouseExited(evt);
            }
        });
        jPanelTransacciones.add(jLabelBotonTransacciones);
        jLabelBotonTransacciones.setBounds(0, 0, 290, 50);

        jPanelDeposito.setBackground(new java.awt.Color(0, 51, 102));
        jPanelDeposito.setPreferredSize(new java.awt.Dimension(290, 50));

        jLabelBotonDeposito.setBackground(new java.awt.Color(68, 114, 196));
        jLabelBotonDeposito.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelBotonDeposito.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBotonDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/billetera.png"))); // NOI18N
        jLabelBotonDeposito.setText("Depósito      ");
        jLabelBotonDeposito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelBotonDeposito.setOpaque(true);
        jLabelBotonDeposito.setPreferredSize(new java.awt.Dimension(290, 50));
        jLabelBotonDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonDepositoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBotonDepositoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotonDepositoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelDepositoLayout = new javax.swing.GroupLayout(jPanelDeposito);
        jPanelDeposito.setLayout(jPanelDepositoLayout);
        jPanelDepositoLayout.setHorizontalGroup(
            jPanelDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDepositoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBotonDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelDepositoLayout.setVerticalGroup(
            jPanelDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDepositoLayout.createSequentialGroup()
                .addComponent(jLabelBotonDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelOpcionesTarjetas.setBackground(new java.awt.Color(0, 51, 102));
        jPanelOpcionesTarjetas.setPreferredSize(new java.awt.Dimension(290, 0));
        jPanelOpcionesTarjetas.setLayout(null);

        jLabelPagarOtrasTarjetas.setBackground(new java.awt.Color(68, 114, 196));
        jLabelPagarOtrasTarjetas.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelPagarOtrasTarjetas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPagarOtrasTarjetas.setText("Pagar otras tarjetas");
        jLabelPagarOtrasTarjetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelPagarOtrasTarjetas.setOpaque(true);
        jLabelPagarOtrasTarjetas.setPreferredSize(new java.awt.Dimension(290, 50));
        jLabelPagarOtrasTarjetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPagarOtrasTarjetasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPagarOtrasTarjetasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPagarOtrasTarjetasMouseExited(evt);
            }
        });
        jPanelOpcionesTarjetas.add(jLabelPagarOtrasTarjetas);
        jLabelPagarOtrasTarjetas.setBounds(0, 50, 290, 50);

        jLabelPagarMisTarjetas.setBackground(new java.awt.Color(68, 114, 196));
        jLabelPagarMisTarjetas.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelPagarMisTarjetas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPagarMisTarjetas.setText("Pagar mis tarjetas");
        jLabelPagarMisTarjetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelPagarMisTarjetas.setOpaque(true);
        jLabelPagarMisTarjetas.setPreferredSize(new java.awt.Dimension(290, 50));
        jLabelPagarMisTarjetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPagarMisTarjetasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPagarMisTarjetasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPagarMisTarjetasMouseExited(evt);
            }
        });
        jPanelOpcionesTarjetas.add(jLabelPagarMisTarjetas);
        jLabelPagarMisTarjetas.setBounds(0, 0, 290, 50);

        jPanelPagos.setBackground(new java.awt.Color(0, 51, 102));
        jPanelPagos.setPreferredSize(new java.awt.Dimension(290, 50));

        jLabelBotonPagos.setBackground(new java.awt.Color(68, 114, 196));
        jLabelBotonPagos.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelBotonPagos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBotonPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dinero.png"))); // NOI18N
        jLabelBotonPagos.setText("Pagar Servicios ");
        jLabelBotonPagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelBotonPagos.setOpaque(true);
        jLabelBotonPagos.setPreferredSize(new java.awt.Dimension(290, 50));
        jLabelBotonPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonPagosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBotonPagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotonPagosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelPagosLayout = new javax.swing.GroupLayout(jPanelPagos);
        jPanelPagos.setLayout(jPanelPagosLayout);
        jPanelPagosLayout.setHorizontalGroup(
            jPanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPagosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBotonPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelPagosLayout.setVerticalGroup(
            jPanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagosLayout.createSequentialGroup()
                .addComponent(jLabelBotonPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelHistorial.setBackground(new java.awt.Color(0, 51, 102));
        jPanelHistorial.setPreferredSize(new java.awt.Dimension(290, 50));

        jLabelBotonHistorial.setBackground(new java.awt.Color(68, 114, 196));
        jLabelBotonHistorial.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelBotonHistorial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBotonHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historial-de-transacciones.png"))); // NOI18N
        jLabelBotonHistorial.setText("Historial");
        jLabelBotonHistorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelBotonHistorial.setOpaque(true);
        jLabelBotonHistorial.setPreferredSize(new java.awt.Dimension(290, 50));
        jLabelBotonHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonHistorialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBotonHistorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotonHistorialMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelHistorialLayout = new javax.swing.GroupLayout(jPanelHistorial);
        jPanelHistorial.setLayout(jPanelHistorialLayout);
        jPanelHistorialLayout.setHorizontalGroup(
            jPanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHistorialLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBotonHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelHistorialLayout.setVerticalGroup(
            jPanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistorialLayout.createSequentialGroup()
                .addComponent(jLabelBotonHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelOpcionesTransacciones.setBackground(new java.awt.Color(0, 51, 102));
        jPanelOpcionesTransacciones.setPreferredSize(new java.awt.Dimension(290, 0));
        jPanelOpcionesTransacciones.setLayout(null);

        jLabelTransferencia.setBackground(new java.awt.Color(68, 114, 196));
        jLabelTransferencia.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTransferencia.setText("Transferencia");
        jLabelTransferencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelTransferencia.setOpaque(true);
        jLabelTransferencia.setPreferredSize(new java.awt.Dimension(290, 50));
        jLabelTransferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTransferenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTransferenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTransferenciaMouseExited(evt);
            }
        });
        jPanelOpcionesTransacciones.add(jLabelTransferencia);
        jLabelTransferencia.setBounds(0, 0, 290, 50);

        jPanelCerrarSesion.setBackground(new java.awt.Color(0, 51, 102));
        jPanelCerrarSesion.setPreferredSize(new java.awt.Dimension(290, 50));

        jLabelBotonCerrarSesion.setBackground(new java.awt.Color(68, 114, 196));
        jLabelBotonCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabelBotonCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBotonCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonCerrarSesion.setText("Cerrar Sesión");
        jLabelBotonCerrarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelBotonCerrarSesion.setOpaque(true);
        jLabelBotonCerrarSesion.setPreferredSize(new java.awt.Dimension(290, 50));
        jLabelBotonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBotonCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotonCerrarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCerrarSesionLayout = new javax.swing.GroupLayout(jPanelCerrarSesion);
        jPanelCerrarSesion.setLayout(jPanelCerrarSesionLayout);
        jPanelCerrarSesionLayout.setHorizontalGroup(
            jPanelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBotonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelCerrarSesionLayout.setVerticalGroup(
            jPanelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBotonCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelMiCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelOpcionesTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelTransacciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelOpcionesTransacciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(jPanelIconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelMiCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOpcionesTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTransacciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelOpcionesTransacciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanelPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanelContenido.setBackground(new java.awt.Color(204, 204, 255));
        jPanelContenido.setPreferredSize(new java.awt.Dimension(755, 652));
        jPanelContenido.setLayout(new java.awt.BorderLayout());

        jLabelBotonDesplegarMenu.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        jLabelBotonDesplegarMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBotonDesplegarMenu.setText("≡");
        jLabelBotonDesplegarMenu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelBotonDesplegarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonDesplegarMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelToolBarLayout = new javax.swing.GroupLayout(jPanelToolBar);
        jPanelToolBar.setLayout(jPanelToolBarLayout);
        jPanelToolBarLayout.setHorizontalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createSequentialGroup()
                .addComponent(jLabelBotonDesplegarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelToolBarLayout.setVerticalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBotonDesplegarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addComponent(jPanelToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBotonCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonCerrarSesionMouseClicked
        guiWebBanking.run(guiWebBanking);
        
        this.dispose();
    }//GEN-LAST:event_jLabelBotonCerrarSesionMouseClicked

    private void jLabelBotonCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonCerrarSesionMouseEntered
        jLabelBotonCerrarSesion.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabelBotonCerrarSesionMouseEntered

    private void jLabelBotonCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonCerrarSesionMouseExited
        jLabelBotonCerrarSesion.setBackground(new Color(68, 114, 196));
    }//GEN-LAST:event_jLabelBotonCerrarSesionMouseExited

    private void jLabelBotonInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonInicioMouseEntered
        jLabelBotonInicio.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabelBotonInicioMouseEntered

    private void jLabelBotonInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonInicioMouseExited
        jLabelBotonInicio.setBackground(new Color(68, 114, 196));
    }//GEN-LAST:event_jLabelBotonInicioMouseExited

    private void jLabelBotonMiCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonMiCuentaMouseEntered
        jLabelBotonMiCuenta.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabelBotonMiCuentaMouseEntered

    private void jLabelBotonMiCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonMiCuentaMouseExited
        jLabelBotonMiCuenta.setBackground(new Color(68, 114, 196));
    }//GEN-LAST:event_jLabelBotonMiCuentaMouseExited

    private void jLabelBotonTarjetasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonTarjetasMouseEntered
        jLabelBotonTarjetas.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabelBotonTarjetasMouseEntered

    private void jLabelBotonTarjetasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonTarjetasMouseExited
        jLabelBotonTarjetas.setBackground(new Color(68, 114, 196));
    }//GEN-LAST:event_jLabelBotonTarjetasMouseExited

    private void jLabelBotonTransaccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonTransaccionesMouseEntered
        jLabelBotonTransacciones.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabelBotonTransaccionesMouseEntered

    private void jLabelBotonTransaccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonTransaccionesMouseExited
        jLabelBotonTransacciones.setBackground(new Color(68, 114, 196));
    }//GEN-LAST:event_jLabelBotonTransaccionesMouseExited

    private void jLabelBotonDepositoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonDepositoMouseEntered
        jLabelBotonDeposito.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabelBotonDepositoMouseEntered

    private void jLabelBotonDepositoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonDepositoMouseExited
        jLabelBotonDeposito.setBackground(new Color(68, 114, 196));
    }//GEN-LAST:event_jLabelBotonDepositoMouseExited

    private void jLabelBotonPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonPagosMouseEntered
        jLabelBotonPagos.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabelBotonPagosMouseEntered

    private void jLabelBotonPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonPagosMouseExited
        jLabelBotonPagos.setBackground(new Color(68, 114, 196));
    }//GEN-LAST:event_jLabelBotonPagosMouseExited

    private void jLabelBotonHistorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonHistorialMouseEntered
        jLabelBotonHistorial.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabelBotonHistorialMouseEntered

    private void jLabelBotonHistorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonHistorialMouseExited
        jLabelBotonHistorial.setBackground(new Color(68, 114, 196));
    }//GEN-LAST:event_jLabelBotonHistorialMouseExited

    /**
     * Método que realiza la animación de despliegue de las opciones del apartado
     * para las Tarjetas de crédito
     * @param evt Objeto MouseEvent que representa la acción del mouse, los clicks
     * y la entrada dentro de los dominios de los widgets 
     */
    private void jLabelBotonTarjetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonTarjetasMouseClicked
        Thread hiloPausar = new Thread(){
            @Override
            public void run(){
                if(!jLabelBotonTransacciones.isOpaque()){
                    jLabelBotonTransaccionesMouseClicked(null);
                    try {
                        Thread.sleep(150);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                //si el widget por debajo del jPanelTarjetas se encuentra en su lugar
                //desplaza y despliega las opciones
                if(jPanelTransacciones.getY() <= 330){
                    desplazarAbajoY(jPanelTransacciones, 330+100, 1);
                    desplazarAbajoY(jPanelDeposito, 380+100, 1);
                    desplazarAbajoY(jPanelPagos, 430+100, 1);
                    desplazarAbajoY(jPanelHistorial, 480+100, 1); 
                    desplegarY(jPanelOpcionesTarjetas, 100, 1);
                    jLabelBotonTarjetas.setText("Tarjetas              –");
                    jLabelBotonTarjetas.setOpaque(false);
                //sino las devuelve a su estado original
                }else if(jPanelTransacciones.getY() > 330){
                    desplazarArribaY(jPanelTransacciones, 430-100, 1);
                    desplazarArribaY(jPanelDeposito, 480-100, 1);
                    desplazarArribaY(jPanelPagos, 530-100, 1);
                    desplazarArribaY(jPanelHistorial, 580-100, 1); 
                    plegarY(jPanelOpcionesTarjetas, jPanelOpcionesTarjetas.getHeight(), 1);
                    jLabelBotonTarjetas.setText("Tarjetas              +");
                    jLabelBotonTarjetas.setOpaque(true);
                }
                jLabelBotonTarjetas.repaint();
            }
        }; hiloPausar.start();
        this.repaint();//refresca el jFrame
    }//GEN-LAST:event_jLabelBotonTarjetasMouseClicked
    
    /**
     * Método que efectúa la animación de desplazamiento del menú, de la tool bar 
     * y del jPanel que muestra los contenidos
     * @param evt Objeto MouseEvent que representa la acción del mouse, los clicks
     * y la entrada dentro de los dominios de los widgets 
     */
    private void jLabelBotonDesplegarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonDesplegarMenuMouseClicked
        //realiza la animación de desplace hacia la izquierda y desplegado
        if (jPanelMenu.getX() == 0) {
            desplazarIzquierdaX(jPanelMenu, -291, 1);
            desplegarX(jPanelContenido, 290, 1);
            desplazarIzquierdaX(jPanelContenido, 1, 1);
            desplegarX(jPanelToolBar, 290, 1);
            desplazarIzquierdaX(jPanelToolBar, 1, 1);
            
            //verifica si alguno de los contenidos están abiertos para realizar
            //la animación de despliegue en caso de que sea así
            if(!jLabelBotonInicio.isOpaque()){
                desplegarX(inicio, 290, 1);
                inicio.desplegarComponentes(); //despliega los Componentes contenidos
                                            //en el jPanel
                
            }else if(!jLabelBotonMiCuenta.isOpaque()){
                desplegarX(Panelmicuenta, 290, 1);
                Panelmicuenta.desplegarComponentes();
                
            }else if(!jLabelPagarMisTarjetas.isOpaque()){
                desplegarX(Panelpagarmistarjetas, 290, 1);
                Panelpagarmistarjetas.desplegarComponentes();
                
            }else if(!jLabelPagarOtrasTarjetas.isOpaque()){
                desplegarX(Panelpagarotrastarjetas, 290, 1);
                Panelpagarotrastarjetas.desplegarComponentes();
                
            }else if(!jLabelTransferencia.isOpaque()){
                desplegarX(Paneltransferencia, 290, 1);
                Paneltransferencia.desplegarComponentes();
                
            }else if(!jLabelBotonDeposito.isOpaque()){
                desplegarX(Paneldeposito, 290, 1);
                Paneldeposito.desplegarComponentes();
                
            }else if(!jLabelBotonPagos.isOpaque()){
                desplegarX(Panelpagos, 290, 1);
                Panelpagos.desplegarComponentes();
                
            }else if(!jLabelBotonHistorial.isOpaque()){
                desplegarX(Panelhistorial, 290, 1);
                Panelhistorial.desplegarComponentes();
            }
            
        //realiza la animación de desplace hacia la derecha y plegado
        } else {
            desplazarDerechaX(jPanelMenu, 0, 1);
            desplazarDerechaX(jPanelContenido, 297, 1);
            plegarX(jPanelContenido, 290, 1);
            desplazarDerechaX(jPanelToolBar, 297, 1);
            plegarX(jPanelToolBar, 290, 1);
            
            //verifica si alguno de los contenidos están abiertos para realizar
            //la animación de pliegue en caso de que sea así
            if(!jLabelBotonInicio.isOpaque()){
                plegarX(inicio, 290, 1);
                inicio.plegarComponentes(); //pliega los Componentes contenidos
                                            //en el jPanel
                
            }else if(!jLabelBotonMiCuenta.isOpaque()){
                plegarX(Panelmicuenta, 290, 1);
                Panelmicuenta.plegarComponentes();
                
            }else if(!jLabelPagarMisTarjetas.isOpaque()){
                plegarX(Panelpagarmistarjetas, 290, 1);
                Panelpagarmistarjetas.plegarComponentes();
                
            }else if(!jLabelPagarOtrasTarjetas.isOpaque()){
                plegarX(Panelpagarotrastarjetas, 290, 1);
                Panelpagarotrastarjetas.plegarComponentes();
                
            }else if(!jLabelTransferencia.isOpaque()){
                plegarX(Paneltransferencia, 290, 1);
                Paneltransferencia.plegarComponentes();
                
            }else if(!jLabelBotonDeposito.isOpaque()){
                plegarX(Paneldeposito, 290, 1);
                Paneldeposito.plegarComponentes();
                
            }else if(!jLabelBotonPagos.isOpaque()){
                plegarX(Panelpagos, 290, 1);
                Panelpagos.plegarComponentes();
                
            }else if(!jLabelBotonHistorial.isOpaque()){
                plegarX(Panelhistorial, 290, 1);
                Panelhistorial.plegarComponentes();
            }
        }
        
       
    }//GEN-LAST:event_jLabelBotonDesplegarMenuMouseClicked

    /**
     * Método que utiliza hilos para simular el despliegue y pliegue de las subopciones de 
     * la opción Transacciones del menú, también llama al método mouseclicked que maneja
     * el despliegue y pliegue de las subopciones de Tarjetas en caso de que estas estén
     * desplegadas
     * @param evt Objeto MouseEvent que representa la acción del mouse, los clicks
     * y la entrada dentro de los dominios de los widgets
     */
    private void jLabelBotonTransaccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonTransaccionesMouseClicked
        Thread hiloPausar = new Thread(){ //declara un hilo que genera una pausa entre animaciones de pliegue y despliegue
            @Override
            public void run(){
                if(!jLabelBotonTarjetas.isOpaque()){ //verifica si la opción Tarjetas está clickada
                    jLabelBotonTarjetasMouseClicked(null); //llama al método para plegar las subobciones de Tarjetas
                    try {
                        Thread.sleep(150);   //ayuda a que las animaciones de pliegue y despliegue 
                                            //de Tarjetas y Transacciones
                                           //no se solapen y generen errores
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                //si el widget por debajo del jPanelTarjetas se encuentra en su lugar
                //desplaza y despliega las opciones
                if(jPanelDeposito.getY() <= 380){
                    desplazarAbajoY(jPanelDeposito, 380+50, 1);
                    desplazarAbajoY(jPanelPagos, 430+50, 1);
                    desplazarAbajoY(jPanelHistorial, 480+50, 1); 
                    desplegarY(jPanelOpcionesTransacciones, 50, 1);
                    jLabelBotonTransacciones.setText("Transacciones    –");
                    jLabelBotonTransacciones.setOpaque(false);
                //sino las devuelve a su estado original
                }else if(jPanelDeposito.getY() > 380){
                    desplazarArribaY(jPanelDeposito, 380, 1);
                    desplazarArribaY(jPanelPagos, 430, 1);
                    desplazarArribaY(jPanelHistorial, 480, 1);
                    plegarY(jPanelOpcionesTransacciones, jPanelOpcionesTransacciones.getHeight(), 1);
                    jLabelBotonTransacciones.setText("Transacciones    +");
                    jLabelBotonTransacciones.setOpaque(true);
                }
                jLabelBotonTransacciones.repaint();
            }
        }; hiloPausar.start(); //inicia el hilo
        
        this.repaint();//refresca el jFrame
    }//GEN-LAST:event_jLabelBotonTransaccionesMouseClicked

    /**
     * Método que utiliza hilos para la animación de desplazar jPanels hacia abajo
     * @param jpanel Variable tipo JPanel a desplazar
     * @param finalY Posicion final del JPanel en el eje Y
     * @param time   Variable tipo int para realizar los sleeps en el ciclo
     */
    private void desplazarAbajoY(JPanel jpanel, int finalY, int time){
        Thread hiloDesplazar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){ //sobreescrible el método run de la clase Thread
                //ciclo en donde se relocaliza el widget con un contador
                for(int desplazarY = jpanel.getY(); desplazarY <= finalY; desplazarY++){
                    try {
                        Thread.sleep(time);
                        jpanel.setLocation(jpanel.getX(), desplazarY); //relocaliza el JPanel
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }; hiloDesplazar.start(); //inicia el hilo
    }
    
    /**
     * Método que utiliza hilos para la animación de desplazar jPanels hacia arriba
     * @param jpanel Variable tipo JPanel a desplazar
     * @param finalY Posicion final del JPanel en el eje Y
     * @param time   Variable tipo int para realizar los sleeps en el ciclo
     */
    private void desplazarArribaY(JPanel jpanel, int finalY, int time){
        Thread hiloDesplazar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){ 
                //ciclo en donde se relocaliza el widget con un contador
                for(int desplazarY = jpanel.getY(); desplazarY >= finalY; desplazarY--){
                    try {
                        Thread.sleep(time);
                        jpanel.setLocation(jpanel.getX(), desplazarY); //relocaliza el JPanel
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }; hiloDesplazar.start(); //inicia el hilo
    }
    
    /**
     * Método que utiliza hilos para la animación de desplazar jPanels hacia la izquierda
     * @param jpanel Variable tipo JPanel a desplazar
     * @param finalX Posicion final del JPanel en el eje X
     * @param time   Variable tipo int para realizar los sleeps en el ciclo
     */
    private void desplazarIzquierdaX(JPanel jpanel, int finalX, int time){
        Thread hiloDesplazar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){ //sobreescrible el método run de la clase Thread
                //ciclo en donde se relocaliza el widget con un contador
                for(int desplazarX = jpanel.getX(); desplazarX >= finalX; desplazarX--){
                    try {
                        Thread.sleep(time);
                        jpanel.setLocation(desplazarX, jpanel.getY()); //relocaliza el JPanel
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }; hiloDesplazar.start(); //inicia el hilo
    }
    
    /**
     * Método que utiliza hilos para la animación de desplazar jPanels hacia la derecha
     * @param jpanel Variable tipo JPanel a desplazar
     * @param finalX Posicion final del JPanel en el eje X
     * @param time   Variable tipo int para realizar los sleeps en el ciclo
     */
    private void desplazarDerechaX(JPanel jpanel, int finalX, int time){
        Thread hiloDesplazar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){ //sobreescrible el método run de la clase Thread
                //ciclo en donde se relocaliza el widget con un contador
                for(int desplazarX = jpanel.getX(); desplazarX <= finalX; desplazarX++){
                    try {
                        Thread.sleep(time);
                        jpanel.setLocation(desplazarX, jpanel.getY()); //relocaliza el JPanel
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }; hiloDesplazar.start(); //inicia el hilo
    }
    
    /**
     * Método que cambia la dimensión de un JPanel simulando su despliegue en pantalla
     * @param jpanel          JPanel a ser desplegado
     * @param totalDesplegarY Parámetro tipo int que determina cuanto se sumará a la
     * altura actual del JPanel
     * @param time            Milisegundos para simular los intervalos de la animación
     */
    private void desplegarY(JPanel jpanel, int totalDesplegarY, int time){
        Thread hiloDesplegar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){
                int alturaActual = jpanel.getHeight();
                //ciclo en donde se redimensiona el widget
                for(int desplegarY = alturaActual; desplegarY <= alturaActual+totalDesplegarY; desplegarY++){
                    try {
                        Thread.sleep(time);
                        jpanel.setSize(new Dimension(jpanel.getWidth(), desplegarY)); //redimensiona el JPanel
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }; hiloDesplegar.start(); //inicia el hilo
    }
    
    
    /**
     * Método que cambia la dimensión de un JPanel simulando su plegado
     * @param jpanel JPanel a ser plegado
     * @param totalPlegarY Parámetro que representa el total a ser restado de la
     * altura actual del JPanel
     * @param time   Milisegundos para simular los intervalos de la animación
     */
    private void plegarY(JPanel jpanel, int totalPlegarY, int time){
        Thread hiloplegar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){ 
                int alturaActual = jpanel.getHeight();
                //ciclo en donde se disminuye la dimensión del JPanel de uno en uno
                for(int plegarY = alturaActual; plegarY >= alturaActual-totalPlegarY; plegarY--){ 
                    //captura la excepción InterruptedException generada por .sleep()
                    try {
                        Thread.sleep(time);
                        jpanel.setSize(new Dimension(jpanel.getWidth(), plegarY)); //redimensiona el JPanel
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }; hiloplegar.start(); //comienza el hilo
    }    
    
    /**
     * Método que cambia la dimensión de un JPanel simulando su despliegue en pantalla
     * @param jpanel          JPanel a ser desplegado
     * @param totalDesplegarX Parámetro tipo int que determina cuanto se sumará a la anchura
     * actual del JPanel
     * @param time            Milisegundos para simular los intervalos de la animación
     */
    private void desplegarX(JPanel jpanel, int totalDesplegarX, int time){
        Thread hiloDesplegar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){
                int anchuraActual = jpanel.getWidth();
                //ciclo en donde se redimensiona el widget
                for(int desplegarX = anchuraActual; desplegarX <= anchuraActual+totalDesplegarX; desplegarX++){
                    try {
                        Thread.sleep(time);
                        jpanel.setSize(new Dimension(desplegarX, jpanel.getHeight())); //redimensiona el JPanel
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }; hiloDesplegar.start();
    }
    
    
    /**
     * Método que cambia la dimensión de un JPanel simulando su plegado
     * @param jpanel JPanel a ser plegado
     * @param totalPlegarX Parámetro tipo int que determina cuanto se restará a la anchura
     * actual del JPanel
     * @param time   Milisegundos para simular los intervalos de la animación
     */
    private void plegarX(JPanel jpanel, int totalPlegarX, int time){
        Thread hiloPlegar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){ 
                int anchuraActual = jpanel.getWidth();
                //ciclo en donde se disminuye la dimensión del JPanel de uno en uno
                for(int plegarX = anchuraActual; plegarX >= anchuraActual-totalPlegarX; plegarX--){ 
                    //captura la excepción InterruptedException generada por .sleep()
                    try {
                        Thread.sleep(time);
                        jpanel.setSize(new Dimension(plegarX, jpanel.getHeight())); //redimensiona el JPanel
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }; hiloPlegar.start(); //comienza el hilo
    }
    
    /**
     * Método que toma el evento de click del mouse y agrega en el jPanelContenido
     * un JPanel del tipo inicio
     * @param evt Objeto MouseEvent que representa la acción del mouse, los clicks
     * y la entrada dentro de los dominios de los widgets 
     */
    private void jLabelBotonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonInicioMouseClicked
        if(jLabelBotonInicio.isOpaque())
            desclickearBotonMenu(); //llama a la función que vuelve a la normalidad a los botones
                                //clickeados
        jLabelBotonInicio.setOpaque(false);

        inicio.setLocation(0, 0);//localización de inicio dentro del jPanelContenido
        inicio.setSize(jPanelContenido.getWidth(), jPanelContenido.getHeight());//redimensiona el jpanel inicio
        inicio.mostrarInformacionCliente(cuenta, cliente); //actualiza la información de los jLabels
                                                                //del panel Inicio          
        jPanelContenido.removeAll();
        jPanelContenido.add(inicio); //agrega el jpanel inicio al jpanel de contenidos
        jPanelContenido.revalidate();
        this.repaint();//refresca el jFrame
    }//GEN-LAST:event_jLabelBotonInicioMouseClicked

    /**
     * 
     * @param evt 
     */
    private void jLabelBotonMiCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonMiCuentaMouseClicked
        if(jLabelBotonMiCuenta.isOpaque())
            desclickearBotonMenu();//llama a la función que vuelve a la normalidad a los botones
                                //clickeados
                                
        jLabelBotonMiCuenta.setOpaque(false);

        Panelmicuenta.setLocation(0, 0);//localización de inicio dentro del jPanelContenido
        Panelmicuenta.setSize(jPanelContenido.getWidth(), jPanelContenido.getHeight());//redimensiona el jpanel inicio

        Panelmicuenta.mostrarInformacionCliente(cuenta, cliente); //actualiza la información de los jLabels
                                                                //del panel Mi Cuenta        
        jPanelContenido.removeAll();
        jPanelContenido.add(Panelmicuenta); //agrega el jpanel inicio al jpanel de contenidos
        jPanelContenido.revalidate();
        this.repaint();//refresca el jFrame
    }//GEN-LAST:event_jLabelBotonMiCuentaMouseClicked
    
    private void jLabelTransferenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransferenciaMouseEntered
        jLabelTransferencia.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabelTransferenciaMouseEntered

    private void jLabelPagarOtrasTarjetasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagarOtrasTarjetasMouseEntered
        jLabelPagarOtrasTarjetas.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabelPagarOtrasTarjetasMouseEntered

    private void jLabelPagarMisTarjetasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagarMisTarjetasMouseEntered
        jLabelPagarMisTarjetas.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_jLabelPagarMisTarjetasMouseEntered

    private void jLabelPagarOtrasTarjetasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagarOtrasTarjetasMouseExited
        jLabelPagarOtrasTarjetas.setBackground(new Color(68, 114, 196));
    }//GEN-LAST:event_jLabelPagarOtrasTarjetasMouseExited

    private void jLabelPagarMisTarjetasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagarMisTarjetasMouseExited
        jLabelPagarMisTarjetas.setBackground(new Color(68, 114, 196));
    }//GEN-LAST:event_jLabelPagarMisTarjetasMouseExited

    private void jLabelTransferenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransferenciaMouseExited
        jLabelTransferencia.setBackground(new Color(68, 114, 196));
    }//GEN-LAST:event_jLabelTransferenciaMouseExited

    private void jLabelPagarOtrasTarjetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagarOtrasTarjetasMouseClicked
        if(jLabelPagarOtrasTarjetas.isOpaque())
            desclickearBotonSubMenu();//llama a la función que vuelve a la normalidad a los botones
                                //clickeados
        jLabelPagarOtrasTarjetas.setOpaque(false);

        Panelpagarotrastarjetas.setLocation(0, 0);//localización de inicio dentro del jPanelContenido
        Panelpagarotrastarjetas.setSize(jPanelContenido.getWidth(), jPanelContenido.getHeight());//redimensiona el jpanel inicio
        
        jPanelContenido.removeAll();
        jPanelContenido.add(Panelpagarotrastarjetas); //agrega el jpanel inicio al jpanel de contenidos
        jPanelContenido.revalidate();
        this.repaint();//refresca el jFrame
        jLabelBotonTarjetasMouseClicked(null);
    }//GEN-LAST:event_jLabelPagarOtrasTarjetasMouseClicked

    private void jLabelPagarMisTarjetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagarMisTarjetasMouseClicked
        if(jLabelPagarMisTarjetas.isOpaque())
            desclickearBotonSubMenu();//llama a la función que vuelve a la normalidad a los botones
                                //clickeados
        jLabelPagarMisTarjetas.setOpaque(false);

        Panelpagarmistarjetas.setLocation(0, 0);//localización de inicio dentro del jPanelContenido
        Panelpagarmistarjetas.setSize(jPanelContenido.getWidth(), jPanelContenido.getHeight());//redimensiona el jpanel inicio
        
        jPanelContenido.removeAll();
        jPanelContenido.add(Panelpagarmistarjetas); //agrega el jpanel inicio al jpanel de contenidos
        jPanelContenido.revalidate();
        this.repaint();//refresca el jFrame
        jLabelBotonTarjetasMouseClicked(null);
    }//GEN-LAST:event_jLabelPagarMisTarjetasMouseClicked

    private void jLabelTransferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransferenciaMouseClicked
        if(jLabelTransferencia.isOpaque())
            desclickearBotonSubMenu();//llama a la función que vuelve a la normalidad a los botones
                                //clickeados
        jLabelTransferencia.setOpaque(false);

        Paneltransferencia.setLocation(0, 0);//localización de inicio dentro del jPanelContenido
        Paneltransferencia.setSize(jPanelContenido.getWidth(), jPanelContenido.getHeight());//redimensiona el jpanel inicio
        
        jPanelContenido.removeAll();
        jPanelContenido.add(Paneltransferencia); //agrega el jpanel inicio al jpanel de contenidos
        jPanelContenido.revalidate();
        this.repaint();//refresca el jFrame
        jLabelBotonTransaccionesMouseClicked(null);
    }//GEN-LAST:event_jLabelTransferenciaMouseClicked

    private void jLabelBotonDepositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonDepositoMouseClicked
        if(jLabelBotonDeposito.isOpaque())
            desclickearBotonMenu(); //llama a la función que vuelve a la normalidad a los botones
                                //clickeados
        jLabelBotonDeposito.setOpaque(false);

        Paneldeposito.setLocation(0, 0);//localización de inicio dentro del jPanelContenido
        Paneldeposito.setSize(jPanelContenido.getWidth(), jPanelContenido.getHeight());//redimensiona el jpanel inicio
        
        jPanelContenido.removeAll();
        jPanelContenido.add(Paneldeposito); //agrega el jpanel inicio al jpanel de contenidos
        jPanelContenido.revalidate();
        this.repaint();//refresca el jFrame
    }//GEN-LAST:event_jLabelBotonDepositoMouseClicked

    private void jLabelBotonPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonPagosMouseClicked
        if(jLabelBotonPagos.isOpaque())
            desclickearBotonMenu(); //llama a la función que vuelve a la normalidad a los botones
                                //clickeados
        jLabelBotonPagos.setOpaque(false);

        Panelpagos.setLocation(0, 0);//localización de inicio dentro del jPanelContenido
        Panelpagos.setSize(jPanelContenido.getWidth(), jPanelContenido.getHeight());//redimensiona el jpanel inicio
        
        jPanelContenido.removeAll();
        jPanelContenido.add(Panelpagos); //agrega el jpanel inicio al jpanel de contenidos
        jPanelContenido.revalidate();
        this.repaint();//refresca el jFrame
    }//GEN-LAST:event_jLabelBotonPagosMouseClicked

    private void jLabelBotonHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonHistorialMouseClicked
        if(jLabelBotonHistorial.isOpaque())
            desclickearBotonMenu(); //llama a la función que vuelve a la normalidad a los botones
                                //clickeados
        jLabelBotonHistorial.setOpaque(false);

        Panelhistorial.setLocation(0, 0);//localización de inicio dentro del jPanelContenido
        Panelhistorial.setSize(jPanelContenido.getWidth(), jPanelContenido.getHeight());//redimensiona el jpanel inicio
        Panelhistorial.mostrarInformacionCliente(cuenta, persistenceManager);//actualiza la información de los jLabels
                                                                //del panel Historial        
        jPanelContenido.removeAll();
        jPanelContenido.add(Panelhistorial); //agrega el jpanel inicio al jpanel de contenidos
        jPanelContenido.revalidate();
        this.repaint();//refresca el jFrame
    }//GEN-LAST:event_jLabelBotonHistorialMouseClicked

    
    
    /**
     * Vuelve a su estado normal los botones clickeados en el menú principal
     */
    private void desclickearBotonMenu(){
        if(!jLabelBotonInicio.isOpaque()){
            jLabelBotonInicio.setOpaque(true);
        }else if(!jLabelBotonMiCuenta.isOpaque()){
            jLabelBotonMiCuenta.setOpaque(true);
        }else if(!jLabelBotonTarjetas.isOpaque()){
            jLabelBotonTarjetasMouseClicked(null);
        }else if(!jLabelBotonTransacciones.isOpaque()){
            jLabelBotonTransaccionesMouseClicked(null);
        }else if(!jLabelBotonDeposito.isOpaque()){
            jLabelBotonDeposito.setOpaque(true);
        }else if(!jLabelBotonPagos.isOpaque()){
            jLabelBotonPagos.setOpaque(true);
        }else if(!jLabelBotonHistorial.isOpaque()){
            jLabelBotonHistorial.setOpaque(true);
        }
        
        if(!jLabelPagarMisTarjetas.isOpaque()){
            jLabelPagarMisTarjetas.setOpaque(true);
        }else if(!jLabelPagarOtrasTarjetas.isOpaque()){
            jLabelPagarOtrasTarjetas.setOpaque(true);
        }else if(!jLabelTransferencia.isOpaque()){
            jLabelTransferencia.setOpaque(true);
        }
    } 
    
    /**
     * Vuelve a su estado normal los botones del menú principal excepto al de transacciones
     * y tarjetas, manejando los casos de los botones de los sub menús
     */
    private void desclickearBotonSubMenu(){
        if(!jLabelBotonInicio.isOpaque()){
            jLabelBotonInicio.setOpaque(true);
        }else if(!jLabelBotonMiCuenta.isOpaque()){
            jLabelBotonMiCuenta.setOpaque(true);
        }else if(!jLabelBotonDeposito.isOpaque()){
            jLabelBotonDeposito.setOpaque(true);
        }else if(!jLabelBotonPagos.isOpaque()){
            jLabelBotonPagos.setOpaque(true);
        }else if(!jLabelBotonHistorial.isOpaque()){
            jLabelBotonHistorial.setOpaque(true);
        }
        
        if(!jLabelPagarMisTarjetas.isOpaque()){
            jLabelPagarMisTarjetas.setOpaque(true);
        }else if(!jLabelPagarOtrasTarjetas.isOpaque()){
            jLabelPagarOtrasTarjetas.setOpaque(true);
        }else if(!jLabelTransferencia.isOpaque()){
            jLabelTransferencia.setOpaque(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBotonCerrarSesion;
    private javax.swing.JLabel jLabelBotonDeposito;
    private javax.swing.JLabel jLabelBotonDesplegarMenu;
    private javax.swing.JLabel jLabelBotonHistorial;
    private javax.swing.JLabel jLabelBotonInicio;
    private javax.swing.JLabel jLabelBotonMiCuenta;
    private javax.swing.JLabel jLabelBotonPagos;
    private javax.swing.JLabel jLabelBotonTarjetas;
    private javax.swing.JLabel jLabelBotonTransacciones;
    private javax.swing.JLabel jLabelIconoMenu;
    private javax.swing.JLabel jLabelPagarMisTarjetas;
    private javax.swing.JLabel jLabelPagarOtrasTarjetas;
    private javax.swing.JLabel jLabelTituloMenu;
    private javax.swing.JLabel jLabelTransferencia;
    private javax.swing.JPanel jPanelCerrarSesion;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JPanel jPanelDeposito;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelHistorial;
    private javax.swing.JPanel jPanelIconoMenu;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelMiCuenta;
    private javax.swing.JPanel jPanelOpcionesTarjetas;
    private javax.swing.JPanel jPanelOpcionesTransacciones;
    private javax.swing.JPanel jPanelPagos;
    private javax.swing.JPanel jPanelTarjetas;
    private javax.swing.JPanel jPanelToolBar;
    private javax.swing.JPanel jPanelTransacciones;
    // End of variables declaration//GEN-END:variables

    /**
     * Clase FondoPanel que extiende JPanel y muestra una imagen de fondo.
     */
    class FondoPanel extends JPanel {
        private final Image imagen;

        /**
         * Constructor de la clase. Carga la imagen en el fondo.
         */
        public FondoPanel() {
            // Carga la imagen desde el recurso del proyecto
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondobanco.jpg")).getImage();

            // Establece la opacidad del panel como transparente
            setOpaque(false);
        }

        /**
         * Método paint que se llama automáticamente cuando se necesita pintar el componente.
         * @param g El contexto gráfico utilizado para dibujar.
         */
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);

            // Dibuja la imagen en el fondo del panel con el tamaño del panel
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    }
}
