package Contenidos;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;

import clasesSWB.Cuenta;
import clasesSWB.Cliente;
import clasesSWB.PersistenceManager;


/**
 *
 * @author MAN-U
 */
public class Inicio extends javax.swing.JPanel implements Interface_Panel {
    private PersistenceManager persistenceManager;
    /**
     * Creates new form Inicio
     */
    public Inicio(PersistenceManager persistenceManager) {
        initComponents();
        changeComponentsProperties();
        this.persistenceManager =persistenceManager;
    }
    
    /**
     * Método que cambia el color y la transparencia del jPanel. 
     */
    @Override
    public final void changeComponentsProperties(){
        this.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * Llama al método desplegarX para desplegar de manera horizontal cada uno de los 
     * componentes contenidos en el jPanel
     */
    @Override
    public void desplegarComponentes(){
        desplegarX(JLabelBienvenido, 290, 1);
        desplegarX(jLabelTituloInicio, 290, 1);
        desplegarX(jLabelSaldo, 290, 1);
        desplegarX(jLabelSaldoActualCuenta, 290, 1);
        desplegarX(jPanelInicio, 290, 1);
        
    }
    
    /**
     * Llama al método plegarX para plegar de manera horizontal cada uno de los 
     * componentes contenidos en el jPanel
     */
    @Override
    public void plegarComponentes(){
        plegarX(JLabelBienvenido, 290, 1);
        plegarX(jLabelTituloInicio, 290, 1);
        plegarX(jLabelSaldo, 290, 1);
        plegarX(jLabelSaldoActualCuenta, 290, 1);
        plegarX(jPanelInicio, 290, 1);
    }
    
    /**
     * Método que cambia la dimensión de un Component simulando su despliegue en pantalla
     * @param jcomponent      Component a ser desplegado
     * @param totalDesplegarX Parámetro tipo int que determina cuanto se sumará a la anchura
     * actual del JPanel
     * @param time            Milisegundos para simular los intervalos de la animación
     */
    @Override
    public void desplegarX(Component jcomponent, int totalDesplegarX, int time){
        Thread hiloDesplegar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){
                int anchuraActual = jcomponent.getWidth();
                //ciclo en donde se redimensiona el widget
                for(int desplegarX = anchuraActual; desplegarX <= anchuraActual+totalDesplegarX; desplegarX++){
                    try {
                        Thread.sleep(time);
                        jcomponent.setSize(new Dimension(desplegarX, jcomponent.getHeight())); //redimensiona el JPanel
                    } catch (InterruptedException ex) {
                        System.err.print("No se pudo desplegar el Component");
                    }
                }
            }
        }; hiloDesplegar.start();
    }
    
    
    /**
     * Método que cambia la dimensión de un Component simulando su plegado
     * @param jcomponent   Component a ser plegado
     * @param totalPlegarX Parámetro tipo int que determina cuanto se restará a la anchura
     * actual del JPanel
     * @param time   Milisegundos para simular los intervalos de la animación
     */
    @Override
    public void plegarX(Component jcomponent, int totalPlegarX, int time){
        Thread hiloPlegar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){ 
                int anchuraActual = jcomponent.getWidth();
                //ciclo en donde se disminuye la dimensión del JPanel de uno en uno
                for(int plegarX = anchuraActual; plegarX >= anchuraActual-totalPlegarX; plegarX--){ 
                    //captura la excepción InterruptedException generada por .sleep()
                    try {
                        Thread.sleep(time);
                        jcomponent.setSize(new Dimension(plegarX, jcomponent.getHeight())); //redimensiona el JPanel
                    } catch (InterruptedException ex) {
                        System.err.print("No se pudo plegar el Component");
                    }
                }
            }
        }; hiloPlegar.start(); //comienza el hilo
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelBienvenido = new javax.swing.JLabel();
        jLabelTituloInicio = new javax.swing.JLabel();
        jPanelInicio = new javax.swing.JPanel();
        jLabelSaldoActualCuenta = new javax.swing.JLabel();
        jLabelSaldo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(755, 652));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        JLabelBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        JLabelBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        JLabelBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelBienvenido.setText("Bienvenido {nombre}");
        JLabelBienvenido.setPreferredSize(new java.awt.Dimension(755, 140));

        jLabelTituloInicio.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTituloInicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloInicio.setText("Inicio");
        jLabelTituloInicio.setMaximumSize(new java.awt.Dimension(1366, 748));
        jLabelTituloInicio.setPreferredSize(new java.awt.Dimension(755, 32));

        jPanelInicio.setBackground(new java.awt.Color(68, 114, 196));

        jLabelSaldoActualCuenta.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelSaldoActualCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldoActualCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSaldoActualCuenta.setText("SALDO ACTUAL EN LA CUENTA:");
        jLabelSaldoActualCuenta.setMaximumSize(new java.awt.Dimension(1366, 748));
        jLabelSaldoActualCuenta.setPreferredSize(new java.awt.Dimension(755, 32));

        jLabelSaldo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSaldo.setText("$$$ DOLARES ");
        jLabelSaldo.setMaximumSize(new java.awt.Dimension(1366, 748));
        jLabelSaldo.setPreferredSize(new java.awt.Dimension(755, 32));

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSaldoActualCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabelSaldoActualCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 413, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTituloInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(377, 377, 377))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelTituloInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jPanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelBienvenido;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelSaldoActualCuenta;
    private javax.swing.JLabel jLabelTituloInicio;
    private javax.swing.JPanel jPanelInicio;
    // End of variables declaration//GEN-END:variables

    public void mostrarInformacionCliente(Cuenta cuenta, Cliente cliente){
        // Mostrar la informacion en el jPanel Inicio
        JLabelBienvenido.setText("Bienvenido " + cliente.getNombre());
        jLabelSaldo.setText(String.valueOf(cuenta.getSaldo()) + "$");
    }
}
