package Contenidos;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;

import clasesSWB.Cuenta;
import clasesSWB.Cliente;
import clasesSWB.PersistenceManager;

/**
 *
 * @author MAN-U
 */
public class PanelMiCuenta extends javax.swing.JPanel implements Interface_Panel{
    private PersistenceManager persistenceManager;
    /**
     * Creates new form MiCuenta
     */
    public PanelMiCuenta(PersistenceManager persistenceManager) {
        initComponents();
        changeComponentsProperties();
        this.persistenceManager = persistenceManager;
        
    }

    /**
     * Método que cambia el color y la transparencia del jPanel. 
     */
    @Override
    public final void changeComponentsProperties(){
        this.setBackground(new Color(0, 0, 0, 0));
    }
    
    /**
     * Llama al método desplegarX para desplegar de manera horizontal cada uno de los 
     * componentes contenidos en el jPanel
     */
    @Override
    public void desplegarComponentes(){
        desplegarX(JLabelBienvenido, 290, 1);
        desplegarX(jLabelTituloInicio, 290, 1);
        desplegarX(jLabelSaldo, 290, 1);
        desplegarX(jLabelSaldoDisponible, 290, 1);
        desplegarX(jLabelDatosCuenta, 290, 1);
        desplegarX(jLabelNombreUsuario, 290, 1);
        desplegarX(jLabelTituloInicio4, 290, 1);
        desplegarX(jPanelCuenta, 290, 1);
                
    }
    
    /**
     * Llama al método plegarX para plegar de manera horizontal cada uno de los 
     * componentes contenidos en el jPanel
     */
    @Override
    public void plegarComponentes(){
        plegarX(JLabelBienvenido, 290, 1);
        plegarX(jLabelTituloInicio, 290, 1);
        plegarX(jLabelSaldo, 290, 1);
        plegarX(jLabelSaldoDisponible, 290, 1);
        plegarX(jLabelDatosCuenta, 290, 1);
        plegarX(jLabelNombreUsuario, 290, 1);
        plegarX(jLabelTituloInicio4, 290, 1);
        plegarX(jPanelCuenta, 290, 1);
    }
    
    /**
     * Método que cambia la dimensión de un Component simulando su despliegue en pantalla
     * @param jcomponent      Component a ser desplegado
     * @param totalDesplegarX Parámetro tipo int que determina cuanto se sumará a la anchura
     * actual del JPanel
     * @param time            Milisegundos para simular los intervalos de la animación
     */
    @Override
    public void desplegarX(Component jcomponent, int totalDesplegarX, int time){
        Thread hiloDesplegar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){
                int anchuraActual = jcomponent.getWidth();
                //ciclo en donde se redimensiona el widget
                for(int desplegarX = anchuraActual; desplegarX <= anchuraActual+totalDesplegarX; desplegarX++){
                    try {
                        Thread.sleep(time);
                        jcomponent.setSize(new Dimension(desplegarX, jcomponent.getHeight())); //redimensiona el JPanel
                    } catch (InterruptedException ex) {
                        System.err.print("No se pudo desplegar el Component");
                    }
                }
            }
        }; hiloDesplegar.start();
    }
    
    
    /**
     * Método que cambia la dimensión de un Component simulando su plegado
     * @param jcomponent   Component a ser plegado
     * @param totalPlegarX Parámetro tipo int que determina cuanto se restará a la anchura
     * actual del JPanel
     * @param time   Milisegundos para simular los intervalos de la animación
     */
    @Override
    public void plegarX(Component jcomponent, int totalPlegarX, int time){
        Thread hiloPlegar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){ 
                int anchuraActual = jcomponent.getWidth();
                //ciclo en donde se disminuye la dimensión del JPanel de uno en uno
                for(int plegarX = anchuraActual; plegarX >= anchuraActual-totalPlegarX; plegarX--){ 
                    //captura la excepción InterruptedException generada por .sleep()
                    try {
                        Thread.sleep(time);
                        jcomponent.setSize(new Dimension(plegarX, jcomponent.getHeight())); //redimensiona el JPanel
                    } catch (InterruptedException ex) {
                        System.err.print("No se pudo plegar el Component");
                    }
                }
            }
        }; hiloPlegar.start(); //comienza el hilo
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloInicio = new javax.swing.JLabel();
        jPanelCuenta = new javax.swing.JPanel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelDatosCuenta = new javax.swing.JLabel();
        jLabelSaldoDisponible = new javax.swing.JLabel();
        jLabelTituloInicio4 = new javax.swing.JLabel();
        JLabelBienvenido = new javax.swing.JLabel();

        jLabelTituloInicio.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTituloInicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloInicio.setText("Inicio");
        jLabelTituloInicio.setMaximumSize(new java.awt.Dimension(1366, 748));
        jLabelTituloInicio.setPreferredSize(new java.awt.Dimension(755, 32));

        setPreferredSize(new java.awt.Dimension(755, 652));

        jPanelCuenta.setBackground(new java.awt.Color(68, 114, 196));

        jLabelSaldo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSaldo.setText("$$$ DOLARES ");
        jLabelSaldo.setMaximumSize(new java.awt.Dimension(1366, 748));
        jLabelSaldo.setPreferredSize(new java.awt.Dimension(755, 32));

        jLabelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreUsuario.setText("[Nombre del Usuario]");
        jLabelNombreUsuario.setMaximumSize(new java.awt.Dimension(1366, 748));
        jLabelNombreUsuario.setPreferredSize(new java.awt.Dimension(755, 32));

        jLabelDatosCuenta.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelDatosCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatosCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDatosCuenta.setText("Caja de Ahorro [Numero de Cuenta] ");
        jLabelDatosCuenta.setMaximumSize(new java.awt.Dimension(1366, 748));
        jLabelDatosCuenta.setPreferredSize(new java.awt.Dimension(755, 32));

        jLabelSaldoDisponible.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelSaldoDisponible.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldoDisponible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSaldoDisponible.setText("Saldo Disponible");
        jLabelSaldoDisponible.setMaximumSize(new java.awt.Dimension(1366, 748));
        jLabelSaldoDisponible.setPreferredSize(new java.awt.Dimension(755, 32));

        javax.swing.GroupLayout jPanelCuentaLayout = new javax.swing.GroupLayout(jPanelCuenta);
        jPanelCuenta.setLayout(jPanelCuentaLayout);
        jPanelCuentaLayout.setHorizontalGroup(
            jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCuentaLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(jPanelCuentaLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSaldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCuentaLayout.setVerticalGroup(
            jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCuentaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSaldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabelTituloInicio4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTituloInicio4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloInicio4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloInicio4.setText("Inicio");
        jLabelTituloInicio4.setMaximumSize(new java.awt.Dimension(1366, 748));
        jLabelTituloInicio4.setPreferredSize(new java.awt.Dimension(755, 32));

        JLabelBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        JLabelBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        JLabelBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelBienvenido.setText("Bienvenido {nombre}");
        JLabelBienvenido.setPreferredSize(new java.awt.Dimension(755, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTituloInicio4, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(370, 370, 370))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelTituloInicio4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jPanelCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelBienvenido;
    private javax.swing.JLabel jLabelDatosCuenta;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelSaldoDisponible;
    private javax.swing.JLabel jLabelTituloInicio;
    private javax.swing.JLabel jLabelTituloInicio4;
    private javax.swing.JPanel jPanelCuenta;
    // End of variables declaration//GEN-END:variables
 
    /**
     * 
     * @param cuenta
     * @param cliente 
     */
    public void mostrarInformacionCliente(Cuenta cuenta, Cliente cliente){
        // Mostrar la informacion en el jPanel Mi Cuenta
        JLabelBienvenido.setText("Bienvenido " + cliente.getNombre());
        jLabelDatosCuenta.setText(cuenta.getTipoCuenta() + " Nº" + cuenta.getIDCuenta());
        jLabelNombreUsuario.setText(cliente.getNombre());
        jLabelSaldo.setText(String.valueOf(cuenta.getSaldo()) + "$");
      
    }
    
}
