package Contenidos;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author MAN-U
 */
public class PanelPagarOtrasTarjetas extends javax.swing.JPanel implements Interface_Panel{

    /**
     * Creates new form PagarOtrasTarjetas
     */
    public PanelPagarOtrasTarjetas() {
        initComponents();
        changeComponentsProperties();
    }

    /**
     * Método que cambia el color y la transparencia del jPanel. 
     */
    @Override
    public final void changeComponentsProperties(){
        this.setBackground(new Color(0, 0, 0, 0));
    }
    
    /**
     * Llama al método desplegarX para desplegar de manera horizontal cada uno de los 
     * componentes contenidos en el jPanel
     */
    @Override
    public void desplegarComponentes(){
        desplegarX(jLabelPagarOtrasTarjetas, 290, 1);
        desplegarX(jLabelTarjetaAPagarIngresar, 290, 1);
        desplegarX(jTextCodigoTarjetaAPagar, 290, 1);
        desplegarX(jLabelMontoAPagar, 290, 1);
        desplegarX(jTextMontoAPagar, 290, 1);
        desplegarX(jButtonConfirmarPagoTarjeta, 290, 1);
        desplegarX(jPanelPagarOtrasTarjetas, 290, 1);
        desplegarX(jLabelPagoMinimo, 290, 1);
        desplegarX(jLabelDatoPagoMinimo, 290, 1);
    }
    
    /**
     * Llama al método plegarX para plegar de manera horizontal cada uno de los 
     * componentes contenidos en el jPanel
     */
    @Override
    public void plegarComponentes(){
        plegarX(jLabelPagarOtrasTarjetas, 290, 1);
        plegarX(jLabelTarjetaAPagarIngresar, 290, 1);
        plegarX(jTextCodigoTarjetaAPagar, 290, 1);
        plegarX(jLabelMontoAPagar, 290, 1);
        plegarX(jTextMontoAPagar, 290, 1);
        plegarX(jButtonConfirmarPagoTarjeta, 290, 1);
        plegarX(jPanelPagarOtrasTarjetas, 290, 1);
        plegarX(jLabelPagoMinimo, 290, 1);
        plegarX(jLabelDatoPagoMinimo, 290, 1);
    }
    
    /**
     * Método que cambia la dimensión de un Component simulando su despliegue en pantalla
     * @param jcomponent      Component a ser desplegado
     * @param totalDesplegarX Parámetro tipo int que determina cuanto se sumará a la anchura
     * actual del JPanel
     * @param time            Milisegundos para simular los intervalos de la animación
     */
    @Override
    public void desplegarX(Component jcomponent, int totalDesplegarX, int time){
        Thread hiloDesplegar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){
                int anchuraActual = jcomponent.getWidth();
                //ciclo en donde se redimensiona el widget
                for(int desplegarX = anchuraActual; desplegarX <= anchuraActual+totalDesplegarX; desplegarX++){
                    try {
                        Thread.sleep(time);
                        jcomponent.setSize(new Dimension(desplegarX, jcomponent.getHeight())); //redimensiona el JPanel
                    } catch (InterruptedException ex) {
                        System.err.print("No se pudo desplegar el Component");
                    }
                }
            }
        }; hiloDesplegar.start();
    }
    
    
    /**
     * Método que cambia la dimensión de un Component simulando su plegado
     * @param jcomponent   Component a ser plegado
     * @param totalPlegarX Parámetro tipo int que determina cuanto se restará a la anchura
     * actual del JPanel
     * @param time   Milisegundos para simular los intervalos de la animación
     */
    @Override
    public void plegarX(Component jcomponent, int totalPlegarX, int time){
        Thread hiloPlegar = new Thread() { //declara un nuevo hilo
            @Override
            public void run(){ 
                int anchuraActual = jcomponent.getWidth();
                //ciclo en donde se disminuye la dimensión del JPanel de uno en uno
                for(int plegarX = anchuraActual; plegarX >= anchuraActual-totalPlegarX; plegarX--){ 
                    //captura la excepción InterruptedException generada por .sleep()
                    try {
                        Thread.sleep(time);
                        jcomponent.setSize(new Dimension(plegarX, jcomponent.getHeight())); //redimensiona el JPanel
                    } catch (InterruptedException ex) {
                        System.err.print("No se pudo plegar el Component");
                    }
                }
            }
        }; hiloPlegar.start(); //comienza el hilo
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPagarOtrasTarjetas = new javax.swing.JPanel();
        jLabelTarjetaAPagarIngresar = new javax.swing.JLabel();
        jTextCodigoTarjetaAPagar = new javax.swing.JTextField();
        jLabelMontoAPagar = new javax.swing.JLabel();
        jTextMontoAPagar = new javax.swing.JTextField();
        jButtonConfirmarPagoTarjeta = new javax.swing.JButton();
        jLabelPagoMinimo = new javax.swing.JLabel();
        jLabelDatoPagoMinimo = new javax.swing.JLabel();
        jLabelPagarOtrasTarjetas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 0, 51));
        setPreferredSize(new java.awt.Dimension(755, 652));

        jPanelPagarOtrasTarjetas.setBackground(new java.awt.Color(68, 114, 196));

        jLabelTarjetaAPagarIngresar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTarjetaAPagarIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTarjetaAPagarIngresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTarjetaAPagarIngresar.setText("Codigo de Tarjeta a Pagar");

        jTextCodigoTarjetaAPagar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelMontoAPagar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelMontoAPagar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMontoAPagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMontoAPagar.setText("Monto a Pagar");

        jTextMontoAPagar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextMontoAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMontoAPagarActionPerformed(evt);
            }
        });

        jButtonConfirmarPagoTarjeta.setBackground(new java.awt.Color(0, 51, 102));
        jButtonConfirmarPagoTarjeta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonConfirmarPagoTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfirmarPagoTarjeta.setText("Confirmar Pago");
        jButtonConfirmarPagoTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarPagoTarjetaActionPerformed(evt);
            }
        });

        jLabelPagoMinimo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelPagoMinimo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPagoMinimo.setText("Pago Minimo");

        jLabelDatoPagoMinimo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelDatoPagoMinimo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatoPagoMinimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDatoPagoMinimo.setText("{pago minimo}");

        jLabelPagarOtrasTarjetas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelPagarOtrasTarjetas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPagarOtrasTarjetas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPagarOtrasTarjetas.setText("PAGAR OTRAS TARJETAS");

        javax.swing.GroupLayout jPanelPagarOtrasTarjetasLayout = new javax.swing.GroupLayout(jPanelPagarOtrasTarjetas);
        jPanelPagarOtrasTarjetas.setLayout(jPanelPagarOtrasTarjetasLayout);
        jPanelPagarOtrasTarjetasLayout.setHorizontalGroup(
            jPanelPagarOtrasTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPagarOtrasTarjetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPagarOtrasTarjetasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPagarOtrasTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMontoAPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addComponent(jLabelPagoMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTarjetaAPagarIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPagarOtrasTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDatoPagoMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(jTextMontoAPagar)
                    .addComponent(jTextCodigoTarjetaAPagar))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPagarOtrasTarjetasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConfirmarPagoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        jPanelPagarOtrasTarjetasLayout.setVerticalGroup(
            jPanelPagarOtrasTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagarOtrasTarjetasLayout.createSequentialGroup()
                .addComponent(jLabelPagarOtrasTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanelPagarOtrasTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextCodigoTarjetaAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTarjetaAPagarIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPagarOtrasTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPagoMinimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDatoPagoMinimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPagarOtrasTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMontoAPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMontoAPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonConfirmarPagoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPagarOtrasTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jPanelPagarOtrasTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextMontoAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMontoAPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMontoAPagarActionPerformed

    private void jButtonConfirmarPagoTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarPagoTarjetaActionPerformed
        JOptionPane.showConfirmDialog(this, "Esta seguro que quiere pagar esta tarjeta?", "Confrimar Pago Tarjeta", WIDTH);
    }//GEN-LAST:event_jButtonConfirmarPagoTarjetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmarPagoTarjeta;
    private javax.swing.JLabel jLabelDatoPagoMinimo;
    private javax.swing.JLabel jLabelMontoAPagar;
    private javax.swing.JLabel jLabelPagarOtrasTarjetas;
    private javax.swing.JLabel jLabelPagoMinimo;
    private javax.swing.JLabel jLabelTarjetaAPagarIngresar;
    private javax.swing.JPanel jPanelPagarOtrasTarjetas;
    private javax.swing.JTextField jTextCodigoTarjetaAPagar;
    private javax.swing.JTextField jTextMontoAPagar;
    // End of variables declaration//GEN-END:variables
}
